package com.ayt.example.mapper.entity;

import java.util.Date;

public class WeekReport {
    /**
     * 主键 id
     */
    private Integer id;

    /**
     * 组别 team_code
     */
    private Integer teamCode;

    /**
     * 项目id project_id
     */
    private Integer projectId;

    /**
     * 项目名称 project_name
     */
    private String projectName;

    /**
     * 需求名称 demand_name
     */
    private String demandName;

    /**
     * 需求编号 demand_id
     */
    private Integer demandId;

    /**
     * 任务名称 task_name
     */
    private String taskName;

    /**
     * 测试人员姓名 tester_name
     */
    private String testerName;

    /**
     * 测试人员工号 tester_code
     */
    private String testerCode;

    /**
     * 第几周 week_year
     */
    private Integer weekYear;

    /**
     * 状态（需求评审、测分编写、分支、主干、上线） status
     */
    private String status;

    /**
     * 开始时间 start_time
     */
    private Date startTime;

    /**
     * 结束时间 end_time
     */
    private Date endTime;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column week_report.id
     *
     * @return the value of week_report.id
     *
     * @mbg.generated
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column week_report.id
     *
     * @param id the value for week_report.id
     *
     * @mbg.generated
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column week_report.team_code
     *
     * @return the value of week_report.team_code
     *
     * @mbg.generated
     */
    public Integer getTeamCode() {
        return teamCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column week_report.team_code
     *
     * @param teamCode the value for week_report.team_code
     *
     * @mbg.generated
     */
    public void setTeamCode(Integer teamCode) {
        this.teamCode = teamCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column week_report.project_id
     *
     * @return the value of week_report.project_id
     *
     * @mbg.generated
     */
    public Integer getProjectId() {
        return projectId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column week_report.project_id
     *
     * @param projectId the value for week_report.project_id
     *
     * @mbg.generated
     */
    public void setProjectId(Integer projectId) {
        this.projectId = projectId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column week_report.project_name
     *
     * @return the value of week_report.project_name
     *
     * @mbg.generated
     */
    public String getProjectName() {
        return projectName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column week_report.project_name
     *
     * @param projectName the value for week_report.project_name
     *
     * @mbg.generated
     */
    public void setProjectName(String projectName) {
        this.projectName = projectName == null ? null : projectName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column week_report.demand_name
     *
     * @return the value of week_report.demand_name
     *
     * @mbg.generated
     */
    public String getDemandName() {
        return demandName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column week_report.demand_name
     *
     * @param demandName the value for week_report.demand_name
     *
     * @mbg.generated
     */
    public void setDemandName(String demandName) {
        this.demandName = demandName == null ? null : demandName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column week_report.demand_id
     *
     * @return the value of week_report.demand_id
     *
     * @mbg.generated
     */
    public Integer getDemandId() {
        return demandId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column week_report.demand_id
     *
     * @param demandId the value for week_report.demand_id
     *
     * @mbg.generated
     */
    public void setDemandId(Integer demandId) {
        this.demandId = demandId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column week_report.task_name
     *
     * @return the value of week_report.task_name
     *
     * @mbg.generated
     */
    public String getTaskName() {
        return taskName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column week_report.task_name
     *
     * @param taskName the value for week_report.task_name
     *
     * @mbg.generated
     */
    public void setTaskName(String taskName) {
        this.taskName = taskName == null ? null : taskName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column week_report.tester_name
     *
     * @return the value of week_report.tester_name
     *
     * @mbg.generated
     */
    public String getTesterName() {
        return testerName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column week_report.tester_name
     *
     * @param testerName the value for week_report.tester_name
     *
     * @mbg.generated
     */
    public void setTesterName(String testerName) {
        this.testerName = testerName == null ? null : testerName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column week_report.tester_code
     *
     * @return the value of week_report.tester_code
     *
     * @mbg.generated
     */
    public String getTesterCode() {
        return testerCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column week_report.tester_code
     *
     * @param testerCode the value for week_report.tester_code
     *
     * @mbg.generated
     */
    public void setTesterCode(String testerCode) {
        this.testerCode = testerCode == null ? null : testerCode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column week_report.week_year
     *
     * @return the value of week_report.week_year
     *
     * @mbg.generated
     */
    public Integer getWeekYear() {
        return weekYear;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column week_report.week_year
     *
     * @param weekYear the value for week_report.week_year
     *
     * @mbg.generated
     */
    public void setWeekYear(Integer weekYear) {
        this.weekYear = weekYear;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column week_report.status
     *
     * @return the value of week_report.status
     *
     * @mbg.generated
     */
    public String getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column week_report.status
     *
     * @param status the value for week_report.status
     *
     * @mbg.generated
     */
    public void setStatus(String status) {
        this.status = status == null ? null : status.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column week_report.start_time
     *
     * @return the value of week_report.start_time
     *
     * @mbg.generated
     */
    public Date getStartTime() {
        return startTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column week_report.start_time
     *
     * @param startTime the value for week_report.start_time
     *
     * @mbg.generated
     */
    public void setStartTime(Date startTime) {
        this.startTime = startTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column week_report.end_time
     *
     * @return the value of week_report.end_time
     *
     * @mbg.generated
     */
    public Date getEndTime() {
        return endTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column week_report.end_time
     *
     * @param endTime the value for week_report.end_time
     *
     * @mbg.generated
     */
    public void setEndTime(Date endTime) {
        this.endTime = endTime;
    }
}